### PR TITLE
small changes on gulp rename and main.js

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.template/pull/17/files#diff-e977eea076d776fb0e8218602ac1e57cR55 ... when we change this also the testPackageFiles.js need to be extended because it's checking this

**Comment by Jey-Cee** [comment]
Can you do this? I am not firm with Chai.

**Comment by Apollon77** [comment]
will do

**Comment by Jey-Cee** [comment]
Thank you Appollon77

**Comment by Jey-Cee** [comment]
@Apollon77 Can you add also test for field license in io-package.json? I found out that a lot of adapter don't use it and in template it wasn't there.
licenses

**Pull request merged**
