### PR TITLE
Es6 Template and Translation Gulp Task

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by AlCalzone** [comment]
Superseded by #32 and #33 - should be closed

**Comment by jogibear9988** [comment]
do we have a ES6 template in generator?
as long as we don‘t have i would leave it open

**Comment by AlCalzone** [comment]
Yup:
https://github.com/ioBroker/create-adapter/blob/master/CHANGELOG.md#180-2019-01-24

**Comment by AlCalzone** [comment]
This is obsolete now.

**Pull request closed without merging**
